import type { NextConfig } from "next";
import legacySeoRedirects from "./legacy-seo-redirects.json";

const nextConfig: NextConfig = {
  experimental: {
    optimizePackageImports: ["lucide-react"],
  },
  // Index pages + per-slug hard redirects from legacy vesmart.vn URLs.
  // Per-item map is generated by `be` `pnpm prisma:migrate-mongo`.
  async redirects() {
    return [
      {
        source: "/bai-viet",
        destination: "/blog",
        permanent: true,
      },
      {
        source: "/san-pham",
        destination: "/products",
        permanent: true,
      },
      {
        source: "/the-loai/:slug",
        destination: "/blog?tag=:slug",
        permanent: true,
      },
      ...legacySeoRedirects,
    ];
  },
  images: {
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    remotePatterns: [
      {
        protocol: "http",
        hostname: "localhost",
      },
      {
        protocol: "https",
        hostname: "placehold.co",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "cdn.vesmart.vn",
        pathname: "/**",
      },


      {
        protocol: "https",
        hostname: "res.cloudinary.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "s.pstatic.net",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "*.r2.dev",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "*.cloudflarestorage.com",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;
